version: "2.0.0"

# Claude Code Process Monitoring Configuration
claude:
  # Enable Claude Code process monitoring
  enabled: true
  
  # How often to check for process state changes (default: 3s)
  poll_interval: "3s"
  
  # Maximum number of Claude processes to track (default: 10)
  max_processes: 10
  
  # How often to clean up stale process data (default: 5m)
  cleanup_interval: "5m"
  
  # How long to wait before considering a process unresponsive (default: 30s)
  state_timeout: "30s"
  
  # How long to wait for a process to start up (default: 10s)
  startup_timeout: "10s"
  
  # Log file patterns to monitor for state detection
  log_paths:
    - "~/.claude/logs"
    - "/tmp/claude-*"
    - "~/.config/claude/logs/*.log"
  
  # Regular expressions for detecting different process states
  state_patterns:
    busy: '(?i)(Processing|Executing|Running|Working on|Analyzing|Generating)'
    idle: '(?i)(Waiting for input|Ready|Idle|Available)'
    waiting: '(?i)(Waiting for confirmation|Press any key|Continue\?|Y/n)'
    error: '(?i)(Error|Failed|Exception|Panic|Fatal)'
  
  # Enable log file parsing for state detection (default: true)
  enable_log_parsing: true
  
  # Enable CPU/memory monitoring for state detection (default: true)
  enable_resource_monitoring: true
  
  # Enable integration with tmux session management (default: true)
  integrate_tmux: true
  
  # Enable integration with git worktree management (default: true)
  integrate_worktrees: true

# Git Worktree Configuration
worktree:
  # Base directory for worktrees (supports Go template syntax)
  # Default: "../.worktrees/{{.Project}}" (sibling directory pattern)
  # This pattern creates worktrees outside the repository to avoid git's constraint
  # that worktree paths cannot be inside the repository
  base_directory: "../.worktrees/{{.Project}}"
  
  # Directory naming pattern for individual worktrees
  # Default: "{{.Branch}}" (just the branch name)
  # Available variables: Project, Branch, Worktree, Timestamp, UserName, Prefix, Suffix
  directory_pattern: "{{.Branch}}"
  
  # Automatically create directories if they don't exist
  auto_directory: true
  
  # Default branch to use when creating new worktrees
  default_branch: "main"

# Example worktree patterns:
# For a project "myapp" with branch "feature/auth", these patterns would create:
# base_directory: "../.worktrees/{{.Project}}" -> ../.worktrees/myapp/
# directory_pattern: "{{.Branch}}" -> feature-auth
# Full path: ../.worktrees/myapp/feature-auth
#
# Alternative patterns:
# base_directory: "/tmp/worktrees/{{.Project}}" -> /tmp/worktrees/myapp/
# directory_pattern: "{{.Project}}-{{.Branch}}" -> myapp-feature-auth
# Full path: /tmp/worktrees/myapp/myapp-feature-auth

# Status hooks will be triggered based on Claude process states
status_hooks:
  enabled: true
  idle:
    enabled: true
    script: "~/.config/ccmgr-ultra/hooks/idle.sh"
    timeout: 30
    async: true
  busy:
    enabled: true
    script: "~/.config/ccmgr-ultra/hooks/busy.sh"
    timeout: 30
    async: true
  waiting:
    enabled: true
    script: "~/.config/ccmgr-ultra/hooks/waiting.sh"
    timeout: 30
    async: true

# Example of how status hooks can respond to Claude states
# ~/.config/ccmgr-ultra/hooks/idle.sh:
# #!/bin/bash
# echo "Claude is now idle in session: $CCMGR_SESSION_ID"
# echo "Working directory: $CCMGR_WORKING_DIR"
# echo "Worktree: $CCMGR_WORKTREE_ID"

# ~/.config/ccmgr-ultra/hooks/busy.sh:
# #!/bin/bash
# echo "Claude is now busy in session: $CCMGR_SESSION_ID"
# # Maybe update window title or send notification

# ~/.config/ccmgr-ultra/hooks/waiting.sh:
# #!/bin/bash
# echo "Claude is waiting for input in session: $CCMGR_SESSION_ID"
# # Maybe bring window to front or send urgent notification