# ccmgr-ultra configuration file
version: "1.0.0"

# Status hooks - scripts executed on Claude Code state changes
status_hooks:
  enabled: true
  idle:
    enabled: true
    script: "~/.config/ccmgr-ultra/hooks/idle.sh"
    timeout: 30
    async: true
  busy:
    enabled: true
    script: "~/.config/ccmgr-ultra/hooks/busy.sh"
    timeout: 30
    async: true
  waiting:
    enabled: true
    script: "~/.config/ccmgr-ultra/hooks/waiting.sh"
    timeout: 30
    async: true

# Worktree lifecycle hooks - scripts executed during worktree operations
worktree_hooks:
  enabled: true
  creation:
    enabled: true
    script: "~/.config/ccmgr-ultra/hooks/creation.sh"
    timeout: 300  # 5 minutes for dependency installation
    async: false  # Wait for completion
  activation:
    enabled: true
    script: "~/.config/ccmgr-ultra/hooks/activation.sh"
    timeout: 60
    async: true   # Don't block session start

# Worktree settings
worktree:
  auto_directory: true
  directory_pattern: "{{.Project}}-{{.Branch}}"
  default_branch: "main"
  cleanup_on_merge: false

# Keyboard shortcuts
shortcuts:
  n: "new_worktree"
  m: "merge_worktree"
  d: "delete_worktree"
  p: "push_worktree"
  c: "continue_session"
  r: "resume_session"
  q: "quit"

# Command settings
commands:
  claude_command: "claude"
  git_command: "git"
  tmux_prefix: "ccmgr"
  environment: {}